import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const paperlogy = localFont({
  src: [
    { path: "./fonts/Paperlogy-1Thin.woff2", weight: "100" },
    { path: "./fonts/Paperlogy-2ExtraLight.woff2", weight: "200" },
    { path: "./fonts/Paperlogy-3Light.woff2", weight: "300" },
    { path: "./fonts/Paperlogy-4Regular.woff2", weight: "400" },
    { path: "./fonts/Paperlogy-5Medium.woff2", weight: "500" },
    { path: "./fonts/Paperlogy-6SemiBold.woff2", weight: "600" },
    { path: "./fonts/Paperlogy-7Bold.woff2", weight: "700" },
    { path: "./fonts/Paperlogy-8ExtraBold.woff2", weight: "800" },
    { path: "./fonts/Paperlogy-9Black.woff2", weight: "900" },
  ],
  variable: "--font-paperlogy",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${paperlogy.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
